Bump python-ipmi to 0.5.7
Avoiding issues like:
AttributeError: 'array.array' object has no attribute 'tostring'
In newer version of python , as this method was deprecated and dropped
already in python 3.9.

Signed-off-by: Petr Balogh <pbalogh@redhat.com>