Fix for get_ceph_default_replica returning None value. (#4861)
* Fix for get_ceph_default_replica returning None value.
In OCS4.9, 'ceph status' doesnot give replica count value. Hence 'ceph mgr dump' command is used.
Added namespace variable in "pvc.create_pvc_snapshot" function call of test_pvc_snapshot_performance.py. This will fix "TypeError: create_pvc_snapshot() missing 1 required positional argument: 'namespace'" error encountered during PR validation and performance regression runs