Test to verify snapshot when PVC usage is at different levels (#2965)
* Test to verify snapshot when PVC usage is at different levels

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Create snapshot_restore_factory fixture

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Remove unused imports

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Disable parent PVC deletion for cephfs due to bug 1854501

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Move pvc import to the function

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Fix - pass storage class name

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Add snapshot_factory

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Change loop variable name to avoid shadowing

flake8 run-test: commands[0] | flake8 ocs_ci tests

tests/conftest.py:2567:17: F402 import 'pvc' from line 84 shadowed by loop variable

ERROR: InvocationError for command /home/travis/build/red-hat-storage/ocs-ci/.tox/flake8/bin/flake8 ocs_ci tests (exited with code 1)

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Address comments

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Minor improvements

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Minor update

Signed-off-by: Jilju Joy <jijoy@redhat.com>

* Reorder fixtures for proper teardown

Signed-off-by: Jilju Joy <jijoy@redhat.com>