Allow TimeoutIterator to pass timeout and sleep to TimeoutSampler as func arguments
If func in called TimeoutSampler takes timeout or sleep as parameter
it conflicts with parameters timeout and sleep in TimeoutSampler itself
causing issues like:
TypeError: TimeoutSampler.__init__() got multiple values for argument
'timeout'

In case we want to acieve this, we need to rename and pass those params
as func_timeout or func_sleep, and those will be then passeed correctly
as a workaround.

Signed-off-by: Petr Balogh <pbalogh@redhat.com>