Add wait for the toolbox
As the process is now more quick when we don't create cephfs, we need to
add wait for toolbox pod to be running to avoid the error:
AssertionError: No running Ceph tools pod found

Signed-off-by: Petr Balogh <pbalogh@redhat.com>